#!/bin/bash
set -e
exec 2>&1

: ${CLUSTER:=ceph}

CEPH_OPTS="--cluster ${CLUSTER}"

# ensure OSD is running
sv start ceph-osd || exit 1

if [ ! -e /var/lib/ceph/mds/${CLUSTER}-0/keyring ]; then
  # create ceph filesystem
  ceph ${CEPH_OPTS} osd pool create cephfs_data 8
  ceph ${CEPH_OPTS} osd pool create cephfs_metadata 8
  ceph ${CEPH_OPTS} fs new cephfs cephfs_metadata cephfs_data

  # bootstrap MDS
  mkdir -p /var/lib/ceph/mds/${CLUSTER}-0
  ceph ${CEPH_OPTS} auth get-or-create mds.0 mds 'allow' osd 'allow *' mon 'allow profile mds' > /var/lib/ceph/mds/${CLUSTER}-0/keyring
fi

exec ceph-mds ${CEPH_OPTS} -f -i 0
